author: "Kushal Samant"
description: "Official Site / Visual Arts"
email: kushaldsamant@gmail.com
google_analytics: UA-105795582-1
keywords: "Architecture, CSS, HTML, Javascript, People, Places, Visual Art, Web"
logo: /assets/img/kushal_samant_profile_picture.png
minimal: 
  date_format: "%b %-d, %Y"
  social_links: 
    github: kvshvlin
    instagram: yourmailproject
    linkedin: kvshvlin
    youtube_channel: https://www.youtube.com/channel/UCQCznCqUhALucLSk6N8ROPA
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
show_downloads: true
theme: jekyll-theme-minimal
title: Your Mail Project
